server:
  port: 8080

#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nb_data_report?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: root
    # 使用druid数据源，自动生成代码
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      validationQuery: select 1
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      max-active: 10
      min-idle: 1
      max-wait: 6000
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true